name: Build macOS Wallet

on:
  workflow_dispatch:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build-macos-universal:
    name: Build macOS (Universal)
    runs-on: macos-13
    timeout-minutes: 120
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: System Information
      run: |
        echo "🍎 macOS Build Environment"
        echo "=========================="
        echo "macOS Version: $(sw_vers -productVersion)"
        echo "Architecture: $(uname -m)"
        echo "Available CPUs: $(sysctl -n hw.ncpu)"

    - name: Install Dependencies
      continue-on-error: true
      run: |
        echo "📦 Installing dependencies..."
        set +e  # Don't exit on errors
        
        brew update
        
        # Install all required dependencies including libfmt
        brew install \
          automake \
          libtool \
          boost \
          miniupnpc \
          libnatpmp \
          pkg-config \
          python@3.11 \
          qt@5 \
          zmq \
          qrencode \
          protobuf \
          fmt \
          openssl \
          libevent \
          sqlite
        
        # Try to install berkeley-db4, but don't fail if it's deprecated
        brew install berkeley-db4 || echo "berkeley-db4 not available from Homebrew, will install from source"
        
        echo "✅ Dependencies installed"
        set -e

    - name: Install Berkeley DB 4.8 from source
      run: |
        echo "🔧 Installing Berkeley DB 4.8 from source with proper C++ support..."
        cd /tmp
        
        # Download Berkeley DB 4.8.30
        curl -O https://download.oracle.com/berkeley-db/db-4.8.30.tar.gz
        tar xzf db-4.8.30.tar.gz
        cd db-4.8.30
        
        # Apply patches for modern systems
        sed -i.bak 's/__atomic_compare_exchange/__atomic_compare_exchange_db/g' dbinc/atomic.h || true
        
        cd build_unix
        
        # Configure with C++ support and proper flags for macOS
        ../dist/configure \
          --prefix=/usr/local \
          --enable-cxx \
          --enable-static \
          --disable-shared \
          --disable-replication \
          --with-pic \
          CFLAGS="-fPIC -O2" \
          CXXFLAGS="-fPIC -O2 -std=c++11"
        
        # Build and install
        make -j$(sysctl -n hw.ncpu)
        sudo make install
        
        # Verify installation
        echo "✅ Berkeley DB installed:"
        ls -la /usr/local/include/db*
        ls -la /usr/local/lib/libdb*
        
        cd ${{ github.workspace }}

    - name: Setup Python Environment
      run: |
        echo "🐍 Setting up Python environment..."
        
        # Force link Python, ignoring conflicts
        brew link --overwrite --force python@3.11 2>/dev/null || echo "Python linking completed"
        
        # Use the Homebrew Python directly
        PYTHON="/usr/local/opt/python@3.11/bin/python3.11"
        
        if [ -f "$PYTHON" ]; then
          echo "✅ Using Homebrew Python: $PYTHON"
          $PYTHON --version
          $PYTHON -m pip install --break-system-packages --upgrade pip setuptools wheel 2>/dev/null || echo "Python setup completed"
        else
          echo "Using system Python"
          python3 -m pip install --break-system-packages --upgrade pip setuptools wheel 2>/dev/null || echo "Python setup completed"
        fi

    - name: Install Protobuf 3.6.1 from source
      run: |
        echo "🔧 Installing Protobuf 3.6.1 from source..."
        mkdir -p ${{ github.workspace }}/local
        cd ${{ github.workspace }}/local
        
        curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz | tar xz
        cd protobuf-3.6.1
        
        ./configure --prefix=${{ github.workspace }}/local/protobuf-3.6.1 --disable-shared --enable-static
        make -j$(sysctl -n hw.ncpu)
        make install
        
        echo "✅ Protobuf 3.6.1 installed"

    - name: Fix file permissions
      run: |
        echo "🔧 Fixing file permissions..."
        find . -name "*.sh" -exec chmod +x {} \;
        find . -name "config.guess" -exec chmod +x {} \;
        find . -name "config.sub" -exec chmod +x {} \;
        find . -name "configure" -exec chmod +x {} \;
        if [ -f autogen.sh ]; then chmod +x autogen.sh; fi

    - name: Build with wallet support
      env:
        PATH: "${{ github.workspace }}/local/protobuf-3.6.1/bin:/usr/local/bin:/usr/bin:/bin"
        PKG_CONFIG_PATH: "${{ github.workspace }}/local/protobuf-3.6.1/lib/pkgconfig:/usr/local/lib/pkgconfig"
        PROTOC: "${{ github.workspace }}/local/protobuf-3.6.1/bin/protoc"
        LDFLAGS: "-L${{ github.workspace }}/local/protobuf-3.6.1/lib -L/usr/local/lib"
        CPPFLAGS: "-I${{ github.workspace }}/local/protobuf-3.6.1/include -I/usr/local/include"
        CXXFLAGS: "-std=c++17"
        BDB_LIBS: "-L/usr/local/lib -ldb_cxx-4.8"
        BDB_CFLAGS: "-I/usr/local/include"
      run: |
        echo "🔧 Configuring build with wallet support..."
        ./autogen.sh
        
        ./configure \
          --prefix=${{ github.workspace }}/dist \
          --with-boost=/usr/local \
          --with-qt-dir=/usr/local/opt/qt@5 \
          --enable-reduce-exports \
          --disable-bench \
          --disable-gui-tests \
          --disable-tests \
          --with-libs \
          --with-incompatible-bdb \
          PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/opt/qt@5/lib/pkgconfig:${{ github.workspace }}/local/protobuf-3.6.1/lib/pkgconfig" \
          LDFLAGS="-L/usr/local/lib -L${{ github.workspace }}/local/protobuf-3.6.1/lib" \
          CPPFLAGS="-I/usr/local/include -I${{ github.workspace }}/local/protobuf-3.6.1/include" \
          BDB_LIBS="-L/usr/local/lib -ldb_cxx-4.8" \
          BDB_CFLAGS="-I/usr/local/include" \
          LIBS="-lfmt"
        
        echo "🔨 Building Aegisum with full wallet support..."
        make -j$(sysctl -n hw.ncpu)

    - name: Try depends build as fallback
      if: failure()
      continue-on-error: true
      env:
        PATH: "${{ github.workspace }}/local/protobuf-3.6.1/bin:/usr/local/bin:/usr/bin:/bin"
        PKG_CONFIG_PATH: "${{ github.workspace }}/local/protobuf-3.6.1/lib/pkgconfig"
        PROTOC: "${{ github.workspace }}/local/protobuf-3.6.1/bin/protoc"
      run: |
        echo "🔄 Trying depends build as fallback..."
        cd depends
        make HOST=x86_64-apple-darwin -j$(sysctl -n hw.ncpu) || echo "Depends build failed"
        cd ..
        
        if [ -d "depends/x86_64-apple-darwin" ]; then
          ./autogen.sh
          CONFIG_SITE=$PWD/depends/x86_64-apple-darwin/share/config.site ./configure \
            --prefix=/ \
            --enable-reduce-exports \
            --disable-bench \
            --disable-gui-tests
          
          make -j$(sysctl -n hw.ncpu) || echo "Depends-based build failed"
        fi

    - name: Package wallet tools
      run: |
        echo "📦 Packaging macOS wallet tools..."
        mkdir -p aegisum-wallet-tools-macos
        
        # Copy binaries that were built
        for binary in aegisumd aegisum-cli aegisum-tx; do
          if [ -f "src/$binary" ]; then
            cp "src/$binary" aegisum-wallet-tools-macos/
            echo "✅ $binary included"
          else
            echo "⚠️ $binary not found"
          fi
        done
        
        # Check for Qt wallet
        if [ -f src/qt/aegisum-qt ]; then
          cp src/qt/aegisum-qt aegisum-wallet-tools-macos/
          echo "✅ aegisum-qt included"
        else
          echo "⚠️ aegisum-qt not found"
        fi
        
        # Show what we actually built
        echo "📁 Final package contents:"
        ls -la aegisum-wallet-tools-macos/
        
        # Create archive only if we have files
        if [ "$(ls -A aegisum-wallet-tools-macos/)" ]; then
          tar -czf aegisum-wallet-tools-macos.tar.gz aegisum-wallet-tools-macos/
          echo "✅ Archive created successfully"
        else
          echo "❌ No binaries were built"
          exit 1
        fi

    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: aegisum-wallet-tools-macos
        path: aegisum-wallet-tools-macos.tar.gz
        retention-days: 30

    - name: Build Summary
      if: always()
      run: |
        echo "🎉 MACOS BUILD SUMMARY"
        echo "====================="
        if [ -d aegisum-wallet-tools-macos ]; then
          echo "📁 Built files:"
          ls -la aegisum-wallet-tools-macos/
          echo ""
          echo "🔍 Binary details:"
          for binary in aegisum-wallet-tools-macos/*; do
            if [ -f "$binary" ]; then
              echo "$(basename "$binary"): $(file "$binary")"
            fi
          done
        else
          echo "❌ No binaries were built"
        fi
        
        if [ -f aegisum-wallet-tools-macos.tar.gz ]; then
          echo "📊 Archive info:"
          ls -la *.tar.gz
        fi
        
        echo ""
        echo "💰 Wallet support: ENABLED"
        echo "🔧 Berkeley DB: Installed from source"
        echo "🖥️ Qt GUI: Enabled"
